name: Run Tests

# Ejecutar en cada push y pull request
on:
  push:
    branches:
      - cpa  # Cambia "main" si usas otro nombre de rama principal
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Descargar el código del repositorio
      - name: Check out code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Cambia por tu versión de Python

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r pyxations/requirements.txt

      # Ejecutar tests
      - name: Run tests
        run: |
          pytest pyxations/tests
